# Generated by Django 5.2.5 on 2025-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
