# Generated by Django 5.2.5 on 2025-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderator_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
